#ifndef _callback_h
#define _callback_h

/*初始化回调函数族*/
void InitCallback();

enum{
	TM_MUSIC = 0,
	TM_HIT_COUNTDOWN,
	TM_CAST_CD,
	TM_FORCEBAR_CHANGE,
	TM_HIT_POSITION_CHANGE,
	TM_START_HIT,
	TM_FREE_RESET_CUEBALL,
	TM_SHAKE_START_MENU,
	TM_SHAKE,
	TM_LOAD_PAGE,
	TM_LOAD_TEXT,
	TM_SHADES,
	TM_END_SHADES,
	TM_BEGIN_PAGE,
	TM_CHOOSE_GAMEMODE,
	TM_BEGIN_MUSIC,
	TM_PAUSE_MENU,
	TM_PAUSE_MENU_CD,
	TM_LOAD_SAVE,
	TM_GET_THETA,
	TM_START_SIDE,
	TM_REGISTER,
	TM_AI_WAIT,
	TM_AI_SET_CUEBALL,
	TM_AI_PLAY,
	TM_USER,
	TM_PREPARE_TO_HIT,
	TM_WIN,
	TM_CHOOSE_STICK,
	TM_HINT,
};

typedef enum{
	MS_NULL = 0,
	MS_GET_FORCE,
	MS_GET_HIT_POSITION,
	MS_START_HIT,
	MS_FREE_RESET_CUEBALL,
	MS_START_MENU,
	MS_CHOOSE_GAMEMODE,
	MS_PAUSE_MENU,
	MS_LOAD_SAVE,
	MS_REGISTER,
	MS_USER,
	MS_PREPARE_TO_HIT,
	MS_WIN,
	MS_CHOOSE_STICK, 
} MOUSESTATE;

typedef enum{
	KB_NULL = 0,
	KB_GET_FORCE,
	KB_GET_HIT_POSITION,
	KB_START_HIT,
	KB_FREE_RESET_CUEBALL,
	KB_START_MENU,
	KB_CHOOSE_GAMEMODE, 
	KB_PAUSE_MENU,
	KB_LOAD_SAVE,
	KB_REGISTER,
	KB_USER,
	KB_PREPARE_TO_HIT,
	KB_WIN,
	KB_CHOOSE_STICK,
} KEYBOARDSTATE;

#endif
